language: android

android:
  components:
    - build-tools-22.0.0
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    - secure: "lPttF+AikE2/Rtw5CO49XMMD2cLEdOUnswmtMX5rIg4Ot8XZ3zx0tDan/8bvAENZZh2xLbD2e+sHrCCSVpmyH+nHBRu5fMzUZww30gV8GDgwWJqKmQT/TUUdrpPFEYDfEFhy0WtDnw7LO/DwB3MjQVMrp9huzm8UYBGwSIiQ6GI="
    - secure: "Z4LXYWoxV2ZAL3onkc5YIWUo1z8ftVSS6nvfEpc6pBWam5HbTM7XVwzbyr0d9edT/1H+/rVyyZQJ9j1JZjpvX9WA+0RVMTgYU2aVdV/EyaQesNYDZfBr5CUteEj3GFxEIzy0wgWgPfbUb44K577LyB6ra9TdZUdEngCTbXCUmwo="

before_install:
  - export TERM=dumb

  # Create and run emulator
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - ./gradlew -q assemble

script:
#  - android-wait-for-emulator || exit 1
#  - adb shell input keyevent 82 &
  - ./gradlew integrationTest

after_success:
  - ./scripts/deploy_to_maven.sh
